name: deploy to EKS

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: gitops-app
  CLUSTER_NAME: gitops-cluster
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set IMAGE_URI
        run: |
          echo "IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}" >> $GITHUB_ENV
      - name: Checkout code
        uses: actions/checkout@v4

      - name: configure aws creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Login to amazon ecr
        run: |
          aws ecr get-login-password \
          --region $AWS_REGION \
          | docker login \
          --username AWS \
          --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build docker image
        run: |
          docker build -t $IMAGE_URI:$IMAGE_TAG ./app

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_URI }}:${{ env.IMAGE_TAG }}
          format: table
          exit-code: 0
          ignore-unfixed: true

      - name: Push image
        run: |
          docker push $IMAGE_URI:$IMAGE_TAG

      - name: Debug identity
        run: aws sts get-caller-identity

      - name: Terraform security scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform
          skip_check: CKV_AWS_38,CKV_AWS_39,CKV_AWS_130