name: deploy to EKS
on:
  push:
    branches:
      main
env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: gitops-app
  CLUSTER_NAME: gitops-cluster
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: configure aws creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Login to amazon ecr
        run: |
         aws ecr get-login-password \
         --region $AWS_REGION \
          | docker login \
         --username AWS \
         --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com
      - name: build docker images
        run: |
          docker build -t $ECR_REPOSITORY
      - name: tag image
        run: |
          docker tag $ECR_REPOSITORY:latest \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest
      - name: push job
        run: |
          docker push \ 
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:latest
      - name: update kubeconfig
        run: |
          aws eks update-kubeconfig \ 
          --region $AWS_REGION
          --name $CLUSTER_NAME

      - name: deploy to k8s
        run: |
          kubectl apply -f k8s/



